version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: on-failure
